# Generated by Django 4.0.6 on 2023-02-07 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def add_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('app_users', 'Profile')
    
    for user in User.objects.exclude(email__exact=''):
        Profile.objects.create(user=user)
    

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройка сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hint', models.CharField(max_length=50, verbose_name='Кто же это')),
                ('name_note', models.CharField(max_length=200, verbose_name='Примечание')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Емейл подтвержден')),
                ('verify_uid', models.CharField(max_length=200, verbose_name='код для ссылки подтверждения мыла')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.RunPython(add_profiles),
    ]
