# Generated by Django 4.0.6 on 2023-02-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_sitesettings_options_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name_hint',
            field=models.CharField(blank=True, max_length=50, verbose_name='Кто же это'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Примечание'),
        ),
    ]
