# Generated by Django 4.0.6 on 2023-03-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_alter_profile_verify_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='text_value',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
