# Generated by Django 4.0.6 on 2023-03-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_sitesettings_text_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='say_about_new_comments',
            field=models.BooleanField(default=False, verbose_name='Присылать уведомления о новых комментариях'),
        ),
        migrations.AddField(
            model_name='profile',
            name='say_about_new_lesson',
            field=models.BooleanField(default=True, verbose_name='Присылать уведомления о новых уроках'),
        ),
    ]
