# Generated by Django 4.0.6 on 2022-07-28 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название курса')),
                ('about', models.TextField(verbose_name='Описание')),
                ('price', models.CharField(max_length=20, verbose_name='Цена, с пометкой, в какой валюте')),
                ('link', models.URLField(null=True, verbose_name='Ссылка на магазин, где купить')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название урока')),
                ('video', models.URLField(null=True, verbose_name='Видео на ютубе, если есть')),
                ('info', models.TextField(verbose_name='Основная часть урока')),
                ('questions', models.TextField(null=True, verbose_name='Вопросы для домашней работы')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Порядок уроков в курсе')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='app_lessons.course', verbose_name='Часть какого курса')),
            ],
        ),
    ]
