# Generated by Django 4.0.6 on 2022-07-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lessons', '0002_alter_course_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Видео на ютубе, если есть'),
        ),
    ]
