# Generated by Django 4.0.6 on 2022-07-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lessons', '0003_alter_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Цена, с пометкой, в какой валюте'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='questions',
            field=models.TextField(blank=True, null=True, verbose_name='Вопросы для домашней работы'),
        ),
    ]
