# Generated by Django 4.0.6 on 2022-07-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lessons', '0004_alter_course_price_alter_lesson_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('OK', 'Готово'), ('NEW', 'Редактируется')], default='NEW', max_length=3),
        ),
    ]
