# Generated by Django 4.0.6 on 2022-08-07 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_lessons', '0006_category_alter_lesson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='courses', to='app_lessons.category', verbose_name='Категория'),
        ),
    ]
