# Generated by Django 4.0.6 on 2022-08-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lessons', '0008_course_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_intro',
            field=models.BooleanField(default=False, verbose_name='Вводный урок, доступен без покупки курса'),
        ),
    ]
