# Generated by Django 4.0.6 on 2022-08-09 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_lessons', '0009_lesson_is_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesForUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='курс подключен')),
                ('info', models.CharField(blank=True, max_length=200, null=True, verbose_name='примечание')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_users', to='app_lessons.course', verbose_name='курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_courses', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name_plural': 'Подключенные курсы',
                'unique_together': {('course', 'user')},
            },
        ),
    ]
