# Generated by Django 4.0.6 on 2022-08-14 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_lessons', '0010_coursesforusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tmp', verbose_name='файл с картинкой')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Курс бесплатный'),
        ),
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='app_lessons.filepicture', verbose_name='Файл с иллюстрацией'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='app_lessons.filepicture', verbose_name='Файл с иллюстрацией'),
        ),
    ]
