# Generated by Django 4.0.6 on 2022-08-14 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_lessons', '0011_filepicture_alter_course_is_free_course_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='app_lessons.filepicture', verbose_name='Файл с иллюстрацией'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='app_lessons.filepicture', verbose_name='Файл с иллюстрацией'),
        ),
    ]
