# Generated by Django 4.0.6 on 2022-08-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lessons', '0013_alter_category_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.SlugField(null=True, unique=True, verbose_name='Название-урл'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='url',
            field=models.SlugField(null=True, unique=True, verbose_name='Название-урл'),
        ),
    ]
