# Generated by Django 4.0.6 on 2022-08-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lessons', '0014_course_url_lesson_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='is_intro',
            field=models.BooleanField(default=False, verbose_name='Вводный урок'),
        ),
    ]
