# Generated by Django 4.0.6 on 2023-02-25 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_lessons', '0017_alter_coursesforusers_is_active_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='test_answer',
            new_name='text_answer',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='test_question',
            new_name='text_question',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_at'),
        ),
    ]
