# Generated by Django 4.0.6 on 2023-02-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lessons', '0018_rename_test_answer_comment_text_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['ordering'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['ordering'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.AddField(
            model_name='course',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
