# Generated by Django 4.0.6 on 2023-03-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lessons', '0019_alter_category_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Цена'),
        ),
    ]
