# Generated by Django 4.0.6 on 2023-03-15 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_lessons', '0020_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text_answer',
            field=models.TextField(blank=True, null=True, verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text_question',
            field=models.TextField(blank=True, null=True, verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
