# Generated by Django 4.0.6 on 2023-09-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lessons', '0021_comment_is_published_alter_comment_text_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('OK', 'Готово'), ('NEW', 'Редактируется'), ('FLY', 'Новый (Промо)')], default='NEW', max_length=3),
        ),
    ]
